### ISSUE TITLE
Standardize processes in AD

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/anomaly-detection#102]
Copy task list from https://github.com/opensearch-project/opensearch-plugins/issues/41
Here is a meta issue for all plugins to track items which have to be taken care of between RC1 and GA for all the plugins.

- [x]  Plugin branching strategy - created `1.0` and `1.x` branches as finalized in issue [here](https://github.com/opensearch-project/.github/issues/13)
- [x]  Backward compatibility testing
- [x]  ~~DCO checks - should be done by infra~~ From infra team(@peterzhuamazon ), DCO check will not be included for GA release
- [x]  ~~Design Documentation - not finalized - see [here](https://github.com/opensearch-project/opensearch-plugins/issues/42)~~ Removed, added for 1.1.0 instead
- [x]  Broken links check
- [x]  Standardize labels - made changes locally - tracking PR to update the official docs [here](https://github.com/opensearch-project/.github/pull/17)
- [x]  README.md, etc
- [x]  Release Tags
- [x]  Release notes
- [x]  Public Documentation - follow up with base issue [here](https://github.com/opensearch-project/.github/issues/8)
- [x]  Clean up branches
- [x]  Issue and PR templates
- [x]  CI workflows
- [x]  ~~Plugins dependencies from Maven - not done - open issue [here](https://github.com/opensearch-project/opensearch-plugins/issues/45)~~ - Doesn't make sense for GA because plugins would need to build from 1.0 release versions of those dependencies that don’t exist yet.
- [x]  Test coverage reporting - from https://github.com/opensearch-project/opensearch-plugins/issues/46, it's ok to just add test coverage badge in README
- [x]  License header checks
- [x]  Plugin artifact names
- [x]  Branch protection rules - Will be handled by others - details in the issue [here](https://github.com/opensearch-project/opensearch-plugins/issues/52)

**Comment by ylwu-amzn** [comment]
From infra team, DCO check will not be included in GA release, same for plugin dependencies from Maven.

**Comment by dblock** [comment]
Should we close this here?

**Comment by ylwu-amzn** [comment]
sure, close this issue.
