### ISSUE TITLE
[META] AD enhancment in 2.17

### ISSUE THREAD

**Issue by kaituo** [opensearch-project/anomaly-detection#1278]
**Checklist**
- [ ] remote index: enable aggregate data from multiple cluster; enable aggregated view of multiple remote indices.
- [ ] flattened index mapping: Many values are not flattened, making it difficult to view them on the dashboard. For instance, entity values are nested objects, and features are arrays. The requirement is to reference a feature by name and apply conditions like `f1 > 3`. Additionally, there is a need to perform terms aggregation on categorical fields. This will require adjustments to the mapping and the addition of new fields in the result index.
- [ ] missing value imputation: Support filling in zeros, last known value, fixed value.
- [ ] Contextual launch: Contextual launch the detector page from the main dashboard, and then launch the actual logs in Discover page from detector page.
- [ ] rule-based AD: https://github.com/opensearch-project/anomaly-detection/issues/563

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by kaituo** [comment]
@opensearch-project/admin -- Can we please move this to https://github.com/orgs/opensearch-project/projects/1 under 2.17?
