### ISSUE TITLE
[meta] Anomaly Detection: High Cardinality AD enhancements

### ISSUE THREAD

**Issue by sean-zheng-amazon** [opensearch-project/anomaly-detection#190]
This is to enhance the original HCAD from following perspectives:

- [ ] [Improve rate limiting](https://github.com/opensearch-project/anomaly-detection/issues/85)
- [ ] [Add pagination to handle bigger data sets](https://github.com/opensearch-project/anomaly-detection/issues/86)
- [ ] [Add support for multi category fields support](https://github.com/opensearch-project/anomaly-detection/issues/87)
- [ ] [Enable Shingle in HCAD](https://github.com/opensearch-project/anomaly-detection/issues/192)
