### ISSUE TITLE
[Meta] Anomaly Detection: Universal Flow

### ISSUE THREAD

**Issue by sean-zheng-amazon** [opensearch-project/anomaly-detection#191]
We are going to build unified workflow for realtime and historical anomaly detection within the same detector. So user doesn't need to create new historical detectors if they want to use the same realtime detector configuration to do historical anomaly detection, vice versa.

- [ ] [RFC] (https://github.com/opendistro-for-elasticsearch/anomaly-detection/issues/380)
- [ ] [Universal flow feature change] (https://github.com/opensearch-project/anomaly-detection/pull/147)
- [ ] [Backward compatibility] (https://github.com/opensearch-project/anomaly-detection/issues/133)

**Comment by kaituo** [comment]
we have already released the feature
