### ISSUE TITLE
[META] Forecasting in Anomaly Detection 

### ISSUE THREAD

**Issue by brijos** [opensearch-project/anomaly-detection#615]
**Is your feature request related to a problem?**
This is a container to house forecasting feature requirements as they progress.

**What solution would you like?**
[Proposal](https://github.com/opensearch-project/ml-commons/issues/408)

** Working issues

- [x] Milestone 1: create a forecaster
  - [ ] [Indices code (checkpoint, jobs, state)](https://github.com/opensearch-project/anomaly-detection/issues/931)
  - [ ] Updating System index schemas
  - [ ] [refactor common settings, names, etc.](https://github.com/opensearch-project/anomaly-detection/issues/866)
  - [ ] cluster setting like plugins.forecast.enabled to enable/disable forecasting functionality
  - [ ]  [imputation](https://github.com/opensearch-project/anomaly-detection/issues/906)
- [x] Milestone 2: run a forecaster
  - [ ] [Get forecaster result transport](https://github.com/opensearch-project/anomaly-detection/issues/833)
  - [ ] Support shingling
  - [ ] Entry workflow
  - [ ] Rate limit
  - [ ] Feature Preperation (e.g. in HC query to paginate aggregated data)
  - [ ] de-trend
- [x] Milestone 3: support job scheduler
- [x] Milestone 4: [rename to time series analytics](https://github.com/opensearch-project/anomaly-detection/issues/864)
  - [x] BWC testing (mostly for AD since new RCF has [changed](https://github.com/aws/random-cut-forest-by-aws/pull/378) its serde)
- [x] Milestone 5: [functional api](https://github.com/opensearch-project/anomaly-detection/issues/839)
  - [ ] stop forecaster
  - [ ] get forecaster
  - [ ] update forecaster
  - [ ] delete forecaster
  - [ ] search forecaster
  - [ ] top forecasts
  - [ ] result index mapping: easy for querying in UX and alerting
- [x] Milestone 6: monitoring apis
  - [ ] profile (references of ProfileAction in ExecuteResultResponseRecorder and test get task)
  - [ ] stats
  - [ ] search forecast tasks
- [x] Milestone 7: historical forecast
   - [ ] test all existing APIs works for both historical and real time
   - [ ] [forecast task](https://github.com/opensearch-project/anomaly-detection/issues/981)
- [x] Milestone 8: validate api (including forecaster and model level. e.g., max categorical fields honored and infer minimum interval?) and suggest (interval) api
- [x] Milestone 9: fault tolerance
  - [ ] resource (disk and memory) management in hourly and daily cron
  - [ ] circuit breaker
- [x] Milestone 10: upgrade rcf and data quality, recency bias (transformDecay in trcf), minimum shingle = 4
  - [x] [RCFCaster serde](https://github.com/aws/random-cut-forest-by-aws/pull/360)
  - [ ] new model size formula (considering ErrorHandler)
  - [ ] [Data quality](https://github.com/opensearch-project/anomaly-detection/issues/877)
  - [ ] error statistics (tied to UX on how to present them)
  - [x] [upgrade rcf lib](https://github.com/opensearch-project/anomaly-detection/issues/978)
- [x] Milestone 11 default and custom result index, guard against modifying result index, alerting)
  - [ ] Test if custom result index still works or not (e.g., top forecast result api)
- [x] Milestone 12 security
  - [ ] In AD plugin user finds out that they don’t have the write permissions in the very end of the stepper flow, after configuring the model and the detector, which is frustrating (Playground is an example). Can we do the permission check in the beginning of the flow
  - [ ] security tests
- [x] Milestone 13 adjust based on ux design (state transition graph, specify history in cold start)
  - [ ] infer shingle size. Users can solicit shingle size explicitly or implicitly from ux in three ways: shingle size in advanced parameter, user specify seasonality, and users telling us how long they want to forecast.
  - [ ] For the error states user can access content of the full error message in a modal window
  - [ ] allow the compare data source or model parameters changes (e.g., using md5)
  - [ ] validate when users haven't specified interval yet (e.g., look at data source/filter and find the data is almost empty)
  - [ ] specify history in cold start
  - [ ] forecast range (cannot be more/less than a value)
  - [ ] run once stat
- [ ] Milestone 14: bug fix
  - [ ] support > 1 hour interval
- [ ] Milestone 15: unit and integration tests

[Frontend](https://github.com/opensearch-project/ux/issues/70)
- [ ] [Fixed Interval Viz POC](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/441)
- [ ] test light and dark mode (related: https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/572)
- [ ] [test action items still works](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin)/issues/581

**Comment by brijos** [comment]
Added to the [RFC section](https://forum.opensearch.org/t/proposal-forecasting-dev-ops-metrics-and-financial-inventory-metrics/10713) of the user forum

**Comment by amitgalitz** [comment]
We have released the forecasting plugin with all the stated above functionality including supporting over 1 hour intervals in OpenSearch 3.1: https://docs.opensearch.org/latest/observing-your-data/forecast/index/

All documentation can be found here, if anything is found to be missing, we encourage opening a new issue in this repo.
